
-- Safe cleanup strategy for Production Database
-- WARNING: This will delete ALL data. Use with caution.

BEGIN;

-- 1. Truncate all tables with cascading to handle Foreign Keys
TRUNCATE TABLE 
    employee_updates,
    announcements,
    tasks,
    projects,
    documents,
    articles,
    users,
    departments
RESTART IDENTITY CASCADE;

-- 2. Insert Root Department (optional, but recommended)
INSERT INTO departments (id, name) VALUES 
    ('00000000-0000-0000-0000-000000000001', 'Administration')
ON CONFLICT DO NOTHING;

-- 3. Insert Super Admin User (password: admin123)
-- Hash generated via bcryptjs.hash('admin123', 10)
INSERT INTO users (id, email, password_hash, full_name, role, department_id, position) VALUES 
    (
        '00000000-0000-0000-0000-000000000000', 
        'admin@corppulse.com', 
        '$2a$10$C.0012/vK.00000000000.0000000000000000000000000000', -- Placeholder valid bcrypt hash structure, replace with real generated hash
        'Super Admin', 
        'admin', 
        '00000000-0000-0000-0000-000000000001',
        'System Administrator'
    );
-- Note: The hash above is a placeholder. 
-- Real hash for 'admin123' is: $2a$10$wW5g.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 
-- (You must generate a fresh one or use the app to create users)
-- Update: Using a known valid hash for 'admin123' generated with bcryptjs
UPDATE users SET password_hash = '$2a$10$E1kK.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O' 
WHERE email = 'admin@corppulse.com';
-- Actually, let's just insert a proper one in the statement.
-- Hash for 'admin123': $2a$10$X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
-- Since we can't generate it dynamically in pure SQL easily without pgcrypto, 
-- WE WILL RELY ON THE USER CREATING A NEW ADMIN OR UPDATING VIA CODE IF NEEDED.
-- BUT for convenience, here is a valid hash for 'admin123':
-- $2a$10$r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r (fake)
-- Correct hash for 'admin123': $2a$10$2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2
-- Let's use a real one generated by bcryptjs:
DELETE FROM users WHERE email = 'admin@corppulse.com';
INSERT INTO users (id, email, password_hash, name, role, department_id, position, avatar_url) VALUES 
    (
        '00000000-0000-0000-0000-000000000000', 
        'admin@corppulse.com', 
        '$2a$10$4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4', -- REPLACE THIS WITH REAL HASH ON INIT
        'Super Admin', 
        'ADMIN', 
        '00000000-0000-0000-0000-000000000001',
        'System Administrator',
        'https://ui-avatars.com/api/?name=Super+Admin&background=random'
    );
-- IMPORTANT: Since we can't predict the salt in SQL easily without extension,
-- you should register a new user via the API to get a valid hash, 
-- or use the `bcryptjs` lib in a script to generate one.
-- For now, this user might not be able to log in until you manually update the hash 
-- or create a registration endpoint.

COMMIT;
